import type { RepoEnvKeyMetadata, VardashValueKind } from './store';

export interface VardashVarlockSchemaKey {
  key: string;
  kind: VardashValueKind;
  required: boolean;
  description?: string | null;
}

export interface BuildVarlockRunCommandInput {
  schemaPath: string;
  command: readonly [string, ...string[]];
  varlockBin?: string;
}

export interface VarlockRunCommand {
  command: string;
  args: string[];
}

const ENV_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

export function vardashKeyToVarlockSchemaKey(key: RepoEnvKeyMetadata): VardashVarlockSchemaKey {
  return {
    key: key.key,
    kind: key.kind,
    required: key.required,
    description: key.description,
  };
}

export function generateVardashVarlockSchema(keys: readonly VardashVarlockSchemaKey[]): string {
  const lines = [
    '# Generated by vardash for optional Varlock validation/redaction.',
    '# Contains metadata only; resolved vardash values are injected via process env.',
    '# @defaultSensitive=false @defaultRequired=false',
    '# ---',
  ];

  for (const key of [...keys].sort((left, right) => left.key.localeCompare(right.key))) {
    assertValidEnvKey(key.key);
    if (key.description) lines.push(...commentLines(key.description));
    const decorators = [];
    if (key.required) decorators.push('@required');
    if (key.kind === 'secret') decorators.push('@sensitive');
    decorators.push('@type=string');
    lines.push(`# ${decorators.join(' ')}`);
    lines.push(`${key.key}=`);
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

export function buildVarlockRunCommand(input: BuildVarlockRunCommandInput): VarlockRunCommand {
  assertNonEmptyString(input.schemaPath, 'schemaPath');
  for (const arg of input.command) assertNonEmptyString(arg, 'command argument');

  return {
    command: input.varlockBin ?? 'varlock',
    args: ['run', '--path', input.schemaPath, '--inject', 'vars', '--', ...input.command],
  };
}

function assertValidEnvKey(key: string): void {
  if (!ENV_KEY_PATTERN.test(key)) throw new Error('Invalid vardash env key for Varlock schema');
}

function assertNonEmptyString(value: string, label: string): void {
  if (value.length === 0) throw new Error(`Expected non-empty ${label}`);
}

function commentLines(value: string): string[] {
  return value
    .split(/\r?\n/)
    .map((line) => `# ${line.replace(/[\r\n]/g, '')}`);
}
