import { describe, expect, it } from 'vitest';
import { createSplitRegistry, parseSplitIntent, resolveSplitIntent, type AcquirableTarget, type SplitFixtures } from './splitViewContract';
import type { PanelTarget, TrustedDefinition, TrustedTargetRegistry } from './targetRegistry';

const workspaceTarget = (workspaceId: string, surfaceKey: string): PanelTarget => ({ version: 1, kind: 'workspace-surface', workspaceId, surfaceKey });
function definition(key: string, runtime: 'leaseable' | 'recreatable' = 'leaseable'): TrustedDefinition { return { resolve: (context) => ({ rendererKey: `fixture:${key}`, payload: { workspaceId: context.workspaceId }, provenance: 'built-in', capabilities: { sandbox: [], clipboardRead: false, clipboardWrite: false, sameOrigin: false, navigation: 'none' }, runtime: runtime === 'leaseable' ? { kind: 'leaseable-runtime' } : { kind: 'recreatable-transient-runtime', continuity: 'fresh local state' }, splitCompatibility: ['workbench'], equivalenceInputs: [key, context.workspaceId!], sharingInputs: [key, context.workspaceId!] }) }; }
function trustedRegistry(): TrustedTargetRegistry { return { crafts: { 'craft-a': { workspaceId: 'workspace-a', allowedScopes: ['builtin/agent', 'builtin/code', 'builtin/forms'] }, 'craft-b': { workspaceId: 'workspace-b', allowedScopes: ['builtin/agent', 'builtin/code', 'builtin/forms'] } }, workspaces: { 'workspace-a': { available: true, containerRef: '/a' }, 'workspace-b': { available: true, containerRef: '/b' } }, surfaces: { 'builtin/agent': definition('agent'), 'builtin/code': definition('code'), 'builtin/forms': definition('forms', 'recreatable') }, internalRoutes: {}, installedPlugins: new Set(), factories: {}, customUrl: definition('url') }; }
const targetIdentity = (craft: string, key: string, workspace: string) => `${craft}\0${key}:${workspace}`;
function fixtures(): SplitFixtures { return { currentVoyageToken: 'voyage-a', panels: [{ token: 'panel-agent', voyageToken: 'voyage-a', craftId: 'craft-a', target: workspaceTarget('workspace-a', 'builtin/agent') }], voyageCraftIds: ['craft-a', 'craft-b'], candidates: [{ craftId: 'craft-a', surfaceKey: 'code', target: workspaceTarget('workspace-a', 'builtin/code') }, { craftId: 'craft-a', surfaceKey: 'forms', target: workspaceTarget('workspace-a', 'builtin/forms') }, { craftId: 'craft-b', surfaceKey: 'code', target: workspaceTarget('workspace-b', 'builtin/code') }, { craftId: 'craft-b', surfaceKey: 'forms', target: workspaceTarget('workspace-b', 'builtin/forms') }], targetRegistry: trustedRegistry(), runtimes: [{ targetIdentity: targetIdentity('craft-a', 'agent', 'workspace-a'), runtimeId: 'agent-a', generation: 3, hostId: 'durable:agent-a' }, { targetIdentity: targetIdentity('craft-a', 'code', 'workspace-a'), runtimeId: 'code-a', generation: 5, hostId: 'durable:code-a' }, { targetIdentity: targetIdentity('craft-b', 'code', 'workspace-b'), runtimeId: 'code-b', generation: 7, hostId: 'durable:code-b' }] }; }
const query = (extra = '') => `?voyage=voyage-a&split=panel-agent&withSurface=code${extra}`;

describe('trusted query reconstruction', () => {
  it('accepts the approved query and rejects duplicates, omissions, and unknowns', () => { expect(parseSplitIntent(query())).toEqual({ voyageToken: 'voyage-a', invokingPanelToken: 'panel-agent', surfaceKey: 'code' }); for (const value of [query('&split=other'), '?voyage=voyage-a&split=panel-agent', `${query()}&url=https://evil.test`, '?voyage=../x&split=p&withSurface=code']) expect(parseSplitIntent(value)).toBeNull(); });
  it('defaults withCraft to authoritative invoking Craft and scopes equal surface keys', () => { expect(resolveSplitIntent(query(), fixtures())).toMatchObject({ ok: true, invoking: { craftId: 'craft-a' }, selected: { craftId: 'craft-a', runtime: { runtimeId: 'code-a' } } }); expect(resolveSplitIntent(query('&withCraft=craft-b'), fixtures())).toMatchObject({ ok: true, selected: { craftId: 'craft-b', runtime: { runtimeId: 'code-b' } } }); });
  it('fails closed for stale ownership, authorization, capability, and records', () => { const cases: Array<[string, (value: SplitFixtures) => void]> = [['stale-voyage', (value) => { value.currentVoyageToken = 'other'; }], ['invoking-panel-unavailable', (value) => { value.panels = []; }], ['invoking-craft-unavailable', (value) => { value.voyageCraftIds = ['craft-b']; }], ['surface-unauthorized-or-incompatible', (value) => { value.targetRegistry.crafts['craft-a']!.allowedScopes = ['builtin/agent']; }], ['runtime-unavailable', (value) => { value.runtimes = value.runtimes.filter((item) => item.runtimeId !== 'code-a'); }]]; for (const [reason, mutate] of cases) { const value = fixtures(); mutate(value); expect(resolveSplitIntent(query(), value)).toEqual({ ok: false, reason }); } });
  it('resolves recreatable targets through current trusted definitions', () => { expect(resolveSplitIntent('?voyage=voyage-a&split=panel-agent&withSurface=forms', fixtures())).toMatchObject({ ok: true, selected: { runtime: { kind: 'recreatable', continuity: 'fresh local state' } } }); });
});

function acquired(overrides: Partial<AcquirableTarget> & { targetIdentity: string }): AcquirableTarget { const resolution = resolveSplitIntent(query(), fixtures()); if (!resolution.ok) throw new Error('fixture failed'); return { ...resolution.invoking, ...overrides }; }
describe('runtime lifecycle ownership', () => {
  it('pins, acquires by stable identity, and reverse-rolls back with exact transient disposal', () => { const recreatable = acquired({ targetIdentity: 'a-recreatable', runtime: { kind: 'recreatable', continuity: 'fresh' } }); const busy = acquired({ targetIdentity: 'z-leaseable', runtime: { kind: 'leaseable', runtimeId: 'z-runtime', generation: 1, hostId: 'durable:z' } }); const registry = createSplitRegistry([recreatable, busy]); registry.seedLease('z-runtime', 'other-host'); expect(registry.enter(recreatable.targetIdentity, busy.targetIdentity)).toEqual({ ok: false, reason: 'runtime-unavailable-or-busy' }); expect(registry.observation()).toMatchObject({ phase: 'inactive', controllerPins: 0, rollbackCount: 1, disposeCount: 1, events: ['pin', 'entering:1', expect.stringMatching(/^acquire:split:/), expect.stringMatching(/^rollback:split:/), expect.stringMatching(/^dispose:split:/), 'unpin'] }); registry.exit('abort'); expect(registry.observation().disposeCount).toBe(1); });
  it('immediately cleans either leaseable or recreatable member on target/plugin/Voyage invalidation', () => { const first = acquired({ targetIdentity: 'agent', pluginId: 'plugin.agent', runtime: { kind: 'leaseable', runtimeId: 'agent', generation: 1, hostId: 'durable:agent' } }); const second = acquired({ targetIdentity: 'forms', pluginId: 'plugin.forms', runtime: { kind: 'recreatable', continuity: 'fresh' } }); for (const invalidate of [(registry: ReturnType<typeof createSplitRegistry>) => registry.invalidateTarget('forms'), (registry: ReturnType<typeof createSplitRegistry>) => registry.invalidatePlugin('plugin.agent'), (registry: ReturnType<typeof createSplitRegistry>) => registry.invalidatePlugin('plugin.forms'), (registry: ReturnType<typeof createSplitRegistry>) => registry.invalidateVoyage()]) { const registry = createSplitRegistry([first, second]); registry.enter('agent', 'forms'); invalidate(registry); expect(registry.observation()).toMatchObject({ phase: 'inactive', controllerPins: 0, splitOnlyRuntimeCount: 0 }); const count = registry.observation().disposeCount; registry.exit('abort'); expect(registry.observation().disposeCount).toBe(count); } });
  it('suppresses overlapping enter and stale completion after Back', () => { const resolved = resolveSplitIntent(query(), fixtures()); if (!resolved.ok) throw new Error('fixture failed'); const registry = createSplitRegistry([resolved.invoking, resolved.selected]); const pending = registry.beginEnter(resolved.invoking.targetIdentity, resolved.selected.targetIdentity); expect(registry.beginEnter(resolved.invoking.targetIdentity, resolved.selected.targetIdentity)).toEqual({ ok: false, reason: 'split-busy' }); registry.exit('browser-back'); expect(registry.completeEnter((pending as { token: number }).token, resolved.invoking.targetIdentity, resolved.selected.targetIdentity)).toEqual({ ok: false, reason: 'stale-transition' }); });
});
