import { describe, expect, it } from 'vitest';
import { createSplitRegistry, parseSplitIntent, rankCompatibleTargets, resolveSplitIntent, type SplitFixtures, type SplitTarget } from './splitViewContract';
const target = (overrides: Partial<SplitTarget> = {}): SplitTarget => ({ key: 'agent', craftId: 'craft-a', kind: 'agent', splitKeys: ['work'], runtime: { kind: 'leaseable', runtimeId: 'agent-runtime', generation: 1 }, ...overrides });
const fixtures = (): SplitFixtures => ({ currentVoyageId: 'voyage-a', voyages: [{ id: 'voyage-a', panels: [{ token: 'panel-token', targetKey: 'agent' }] }], crafts: [{ id: 'craft-a', voyageId: 'voyage-a', workspaceId: 'workspace-a' }], surfaces: [{ ...target(), installed: true, authorized: true }, { ...target({ key: 'code', kind: 'code', runtime: { kind: 'leaseable', runtimeId: 'code-runtime', generation: 1 } }), installed: true, authorized: true }, { ...target({ key: 'form', runtime: { kind: 'recreatable', surfaceKey: 'form', continuity: 'fresh' } }), installed: true, authorized: true }] });
describe('production-shaped trusted Split route', () => {
  it('parses Voyage and invoking Panel tokens plus allowlisted selectors', () => { expect(parseSplitIntent('/voyages/voyage-a/split/panel-token', '?withCraft=craft-a&withSurface=code')).toEqual({ voyageId: 'voyage-a', invokingPanelToken: 'panel-token', craftId: 'craft-a', surfaceKey: 'code' }); expect(parseSplitIntent('/voyages/voyage-a/split/panel-token', '?withSurface=code')).toMatchObject({ surfaceKey: 'code' }); const badRoutes: Array<[string, string]> = [['/voyages/x/split', '?withSurface=code'], ['/voyages/x/split/p', '?withSurface=code&url=x'], ['/voyages/../split/p', '?withSurface=code']]; for (const [path, search] of badRoutes) expect(parseSplitIntent(path, search)).toBeNull(); });
  it('resolves only current durable records and current trusted definitions', () => { expect(resolveSplitIntent('/voyages/voyage-a/split/panel-token', '?withCraft=craft-a&withSurface=code', fixtures())).toMatchObject({ ok: true, invoking: { key: 'agent' }, selected: { key: 'code' } }); const cases: Array<[string, (f: SplitFixtures) => void]> = [['stale-voyage', (f) => { f.currentVoyageId = 'other'; }], ['invoking-panel-unavailable', (f) => { f.voyages[0]!.panels = []; }], ['craft-unavailable', (f) => { f.crafts = []; }], ['surface-unavailable', (f) => { f.surfaces[1]!.installed = false; }], ['surface-unauthorized', (f) => { f.surfaces[1]!.authorized = false; }], ['no-host', (f) => { f.surfaces[1]!.runtime = { kind: 'unsupported', reason: 'no-host' }; }]]; for (const [reason, mutate] of cases) { const value = fixtures(); mutate(value); expect(resolveSplitIntent('/voyages/voyage-a/split/panel-token', '?withCraft=craft-a&withSurface=code', value)).toEqual({ ok: false, reason }); } });
  it('ranks same-Craft compatible targets without kind assumptions', () => { expect(rankCompatibleTargets(target(), [target({ key: 'z', craftId: 'other', runtime: { kind: 'recreatable', surfaceKey: 'z', continuity: 'fresh' } }), target({ key: 'code', kind: 'code' })]).map((item) => item.key)).toEqual(['code', 'z']); });
});
describe('exclusive lifecycle', () => {
  it('pins before identity-ordered acquisition and rolls back in reverse order', () => { const registry = createSplitRegistry([target({ key: 'z', runtime: { kind: 'leaseable', runtimeId: 'z-runtime', generation: 1 } }), target({ key: 'a', runtime: { kind: 'leaseable', runtimeId: 'a-runtime', generation: 1 } })]); registry.seedLease('z-runtime', 1, 'busy'); expect(registry.enter('z', 'a')).toEqual({ ok: false, reason: 'runtime-busy' }); expect(registry.observation()).toMatchObject({ phase: 'inactive', controllerPins: 0, rollbackCount: 1, events: ['pin', 'entering:1', 'acquire:a-runtime', 'rollback:a-runtime', 'unpin'] }); });
  it('models overlap and Back/abort with transition tokens', () => { const registry = createSplitRegistry([target(), target({ key: 'code', runtime: { kind: 'leaseable', runtimeId: 'code', generation: 1 } })]); const pending = registry.beginEnter('agent', 'code'); expect(pending.ok).toBe(true); expect(registry.beginEnter('agent', 'code')).toEqual({ ok: false, reason: 'split-busy' }); registry.exit('browser-back'); expect(registry.completeEnter((pending as { token: number }).token, 'agent', 'code')).toEqual({ ok: false, reason: 'stale-transition' }); expect(registry.observation()).toMatchObject({ phase: 'inactive', controllerPins: 0 }); });
  it('immediately aborts once on Panel, host, Voyage, or plugin invalidation', () => { for (const invalidate of [(r: ReturnType<typeof createSplitRegistry>) => r.deletePanel('agent-runtime'), (r: ReturnType<typeof createSplitRegistry>) => r.replaceHost('agent-runtime', 2), (r: ReturnType<typeof createSplitRegistry>) => r.invalidateVoyage('craft-a'), (r: ReturnType<typeof createSplitRegistry>) => r.invalidateTarget('agent')]) { const registry = createSplitRegistry([target(), target({ key: 'code', runtime: { kind: 'leaseable', runtimeId: 'code', generation: 1 } })]); registry.enter('agent', 'code'); invalidate(registry); expect(registry.observation()).toMatchObject({ phase: 'inactive', controllerPins: 0, transientControllers: 0 }); const disposed = registry.observation().disposeCount; registry.exit('abort'); expect(registry.observation().disposeCount).toBe(disposed); } });
  it('disposes Split-only runtime exactly once and creates no rows', () => { const registry = createSplitRegistry([target(), target({ key: 'form', runtime: { kind: 'recreatable', surfaceKey: 'form', continuity: 'fresh' } })]); registry.enter('agent', 'form'); expect(registry.observation()).toMatchObject({ phase: 'active', splitOnlyRuntimeCount: 1, panelRows: 0, recencyRows: 0 }); registry.exit('abort'); registry.exit('abort'); expect(registry.observation()).toMatchObject({ disposeCount: 1, controllerPins: 0 }); });
});
