import { createDockview, type DockviewApi, type SerializedDockview } from 'dockview';
import 'dockview/dist/styles/dockview.css';
import { resolvePanelTarget, type CapabilityDescriptor, type PanelTarget, type TrustedTargetRegistry } from './targetRegistry';
import { SurfaceOpeningCoordinator, structuralSnapshot, type AtomicCommit, type OpenIntent, type VoyageState } from './surfaceOpeningCoordinator';
import { DOCKVIEW_LAYOUT_FORMAT_VERSION, PINNED_DOCKVIEW_VERSION, normalizeDockviewTopology, parseDockviewEnvelope } from './snapshotPolicy';

const capabilities: CapabilityDescriptor = { sandbox: [], clipboardRead: false, clipboardWrite: false, sameOrigin: false, navigation: 'none' };
const target = (surfaceKey: string): PanelTarget => ({ version: 1, kind: 'workspace-surface', workspaceId: 'workspace-1', surfaceKey });
const definition = (surfaceKey: string) => ({ resolve: (context: { workspaceId?: string }) => ({ rendererKey: `renderer:${surfaceKey}`, payload: {}, provenance: 'built-in' as const, capabilities, runtime: { kind: 'leaseable-runtime' as const }, splitCompatibility: ['workbench'], equivalenceInputs: [surfaceKey, context.workspaceId!], sharingInputs: [surfaceKey, context.workspaceId!] }) });
const registry: TrustedTargetRegistry = { crafts: { craft: { workspaceId: 'workspace-1', allowedScopes: ['agent', 'code', 'forms'] } }, workspaces: { 'workspace-1': { available: true, containerRef: '/workspace' } }, surfaces: { agent: definition('agent'), code: definition('code'), forms: definition('forms') }, internalRoutes: {}, installedPlugins: new Set(), factories: {}, customUrl: definition('url') };
const dockviewElement = document.querySelector<HTMLElement>('#surface-dockview')!;
const runtimeLayer = document.querySelector<HTMLElement>('#runtime-layer')!;
const status = document.querySelector<HTMLOutputElement>('#surface-status')!;
const runtimes = new Map<string, { element: HTMLIFrameElement; bootId: string }>();
const runtimeActivity = new Map<string, number>();
const disposedRuntimeIds = new Set<string>();
const RELOAD_KEY = 'dockview-surface-opening-reload-v2';
let api!: DockviewApi; let coordinator: SurfaceOpeningCoordinator; let atomicCommits = 0; let coordinatorCommands = 0; let rejectNextCommit = false; let corruptNextLayout = false; let lastCommitError = ''; let committedLayout: unknown; let pendingRuntimeIds = new Set<string>(); let runtimeRegistrations = 0; let runtimeReleases = 0; let agentWindow: Window | null = null; let restoringEnvelope = false;

addEventListener('message', (event) => { const data = event.data as { source?: string; heartbeats?: number }; const runtimeId = [...runtimes].find(([, runtime]) => runtime.element.contentWindow === event.source)?.[0]; if (event.origin === location.origin && runtimeId && data?.source === 'dockview-iframe-contract' && typeof data.heartbeats === 'number') runtimeActivity.set(runtimeId, data.heartbeats); });
function runtimeFor(id: string) { let runtime = runtimes.get(id); if (!runtime) { const element = document.createElement('iframe'); const bootId = crypto.randomUUID(); element.title = `Runtime ${id}`; element.src = `/spikes/dockview-contract/iframe-fixture.html?boot=${bootId}`; element.style.cssText = 'height:100%;width:100%;border:0'; runtime = { element, bootId }; runtimes.set(id, runtime); runtimeRegistrations += 1; } return runtime; }
function createComponent() { const element = document.createElement('div'); element.style.cssText = 'height:100%;width:100%'; let runtime: ReturnType<typeof runtimeFor> | undefined; return { element, init(parameters: { params: Record<string, unknown> }) { runtime = runtimeFor(String(parameters.params.panelId)); element.append(runtime.element); }, dispose() { if (runtime?.element.isConnected) runtimeLayer.append(runtime.element); } }; }
function createApi() { const next = createDockview(dockviewElement, { createComponent, disableFloatingGroups: true }); next.layout(Number.parseInt(dockviewElement.style.width, 10), 420); next.onDidMaximizedGroupChange(() => { if (!restoringEnvelope) renderStatus(); }); return next; }
function baseVoyage(width = 900): VoyageState { return { id: 'voyage-current', width, revision: 0, activationSequence: 1, panels: { agent: { id: 'agent', voyageId: 'voyage-current', craftId: 'craft', target: target('agent'), groupId: 'agent-group', lastActivatedSequence: 1, runtimeId: 'runtime:agent' } }, groups: [{ id: 'agent-group', panelIds: ['agent'], activePanelId: 'agent', rect: { x: 0, y: 0, width, height: 420 } }], maximizedGroupId: null, history: [], historyCursor: 0 }; }
function surface(panel: VoyageState['panels'][string]): string { return panel.target.kind === 'workspace-surface' ? panel.target.surfaceKey : 'surface'; }
function addPanel(id: string, label: string, position?: { direction: 'right' | 'below'; referencePanel: string } | { referencePanel: string }) { api.addPanel({ id, component: 'iframe-panel', title: label, params: { panelId: id }, renderer: 'always', ...(position ? { position } : {}) }); }
function applyProjection(next: VoyageState): void {
  api.clear(); let previous: string | undefined;
  for (const group of next.groups) { let first: string | undefined; for (const id of group.panelIds) { const panel = next.panels[id]; if (!panel) continue; addPanel(id, surface(panel), first ? { referencePanel: first } : previous ? { direction: 'right', referencePanel: previous } : undefined); first ??= id; } if (first) { api.getPanel(group.activePanelId)?.api.setActive(); previous = first; } }
  const mostRecent = Object.values(next.panels).sort((a, b) => (b.lastActivatedSequence ?? -1) - (a.lastActivatedSequence ?? -1) || a.id.localeCompare(b.id))[0];
  if (mostRecent) api.getPanel(mostRecent.id)?.api.setActive();
  if (next.maximizedGroupId) { const group = next.groups.find(({ id }) => id === next.maximizedGroupId); if (group) { api.getPanel(group.activePanelId)?.api.setActive(); api.getPanel(group.activePanelId)?.api.maximize(); } }
}
function hasSameStructure(left: VoyageState, right: VoyageState): boolean {
  return JSON.stringify(left.groups.map(({ panelIds }) => panelIds)) === JSON.stringify(right.groups.map(({ panelIds }) => panelIds));
}
function applyPresentation(next: VoyageState): void {
  for (const group of next.groups) api.getPanel(group.activePanelId)?.api.setActive();
  const mostRecent = Object.values(next.panels).sort((a, b) => (b.lastActivatedSequence ?? -1) - (a.lastActivatedSequence ?? -1) || a.id.localeCompare(b.id))[0];
  if (mostRecent) api.getPanel(mostRecent.id)?.api.setActive();
  if (next.maximizedGroupId) api.getPanel(next.groups.find(({ id }) => id === next.maximizedGroupId)?.activePanelId ?? '')?.api.maximize();
  else if (api.activePanel?.api.isMaximized()) api.activePanel.api.exitMaximized();
}
function normalized(value: unknown) { const result = normalizeDockviewTopology(value); if (!result.ok) throw new Error(result.reason); return result.value; }
function topologyEquals(expected: unknown, actual: unknown): boolean { try { return JSON.stringify(normalized(expected)) === JSON.stringify(normalized(actual)); } catch { return false; } }
function projectionAgrees(): boolean { return committedLayout !== undefined && topologyEquals(committedLayout, canonicalEnvelope()); }
function canonicalEnvelope(): unknown { const snapshot = JSON.parse(JSON.stringify(api.toJSON())) as SerializedDockview; const parsed = parseDockviewEnvelope({ formatVersion: DOCKVIEW_LAYOUT_FORMAT_VERSION, dockviewVersion: PINNED_DOCKVIEW_VERSION, snapshot }); if (!parsed.ok) throw new Error(parsed.reason); return parsed.value; }
function restoreEnvelope(value: unknown): void {
  const parsed = parseDockviewEnvelope(value); if (!parsed.ok) throw new Error(parsed.reason);
  restoringEnvelope = true;
  try {
    if (api.activePanel?.api.isMaximized()) api.activePanel.api.exitMaximized();
    api.fromJSON(parsed.value.snapshot, { reuseExistingPanels: true });
    const activeGroup = parsed.value.snapshot.activeGroup;
    if (!activeGroup) return;
    const findActiveView = (node: unknown): string | undefined => { if (!node || typeof node !== 'object') return undefined; const candidate = node as { type?: string; data?: unknown }; if (candidate.type === 'leaf' && candidate.data && typeof candidate.data === 'object') { const group = candidate.data as { id?: string; activeView?: string }; return group.id === activeGroup ? group.activeView : undefined; } return candidate.type === 'branch' && Array.isArray(candidate.data) ? candidate.data.map(findActiveView).find(Boolean) : undefined; };
    const activeView = findActiveView(parsed.value.snapshot.grid.root);
    if (activeView) api.getPanel(activeView)?.api.setActive();
  } finally { restoringEnvelope = false; }
}
function syncProjectionFromLive(next: VoyageState, maximizePanelId: string | null): void { next.groups = api.groups.map((group) => { const rect = group.element.getBoundingClientRect(); for (const panel of group.panels) next.panels[panel.id]!.groupId = group.id; return { id: group.id, panelIds: group.panels.map(({ id }) => id), activePanelId: group.activePanel!.id, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height } }; }); next.maximizedGroupId = maximizePanelId ? next.panels[maximizePanelId]?.groupId ?? null : null; }
function applyStructuralDelta(previous: VoyageState, next: VoyageState): void {
  const maximizePanelId = next.maximizedGroupId ? next.groups.find(({ id }) => id === next.maximizedGroupId)?.activePanelId ?? null : null;
  const added = Object.keys(next.panels).filter((id) => !previous.panels[id]);
  const changed = Object.values(next.panels).filter((panel) => previous.panels[panel.id] && previous.panels[panel.id]!.groupId !== panel.groupId);
  for (const id of added) addPanel(id, surface(next.panels[id]!), next.panels[id]!.groupId === next.panels.agent!.groupId ? { referencePanel: 'agent' } : { direction: 'right', referencePanel: 'agent' });
  for (const panel of changed) if (!added.includes(panel.id)) api.getPanel(panel.id)?.api.moveTo({ group: api.getPanel('agent')!.group, position: 'right' });
  syncProjectionFromLive(next, maximizePanelId);
  applyPresentation(next);
}
function disposeRuntime(id: string): void { const runtime = runtimes.get(id); if (!runtime) return; runtime.element.contentWindow?.dispatchEvent(new Event('pagehide')); runtime.element.remove(); runtimes.delete(id); disposedRuntimeIds.add(id); runtimeReleases += 1; }
function disposePendingRuntimes(): void { for (const id of pendingRuntimeIds) disposeRuntime(id); pendingRuntimeIds.clear(); }
function liveTopologyEvidence() { const envelope = canonicalEnvelope() as { snapshot: { grid: { root: unknown }; panels: Record<string, unknown> } }; const order: string[] = []; const visit = (node: unknown): void => { if (!node || typeof node !== 'object') return; const value = node as { type?: string; data?: unknown }; if (value.type === 'leaf') { const group = value.data as { activeView?: string }; if (group.activeView) order.push(group.activeView); } else if (Array.isArray(value.data)) value.data.forEach(visit); }; visit(envelope.snapshot.grid.root); const invoking = api.getPanel('agent')?.group.element.getBoundingClientRect(); const right = invoking ? api.groups.map((group) => ({ group, rect: group.element.getBoundingClientRect() })).filter(({ rect }) => rect.left >= invoking.right - 1 && Math.min(rect.bottom, invoking.bottom) > Math.max(rect.top, invoking.top)).sort((a, b) => a.rect.left - b.rect.left)[0]?.group.activePanel?.id : undefined; return { serializedTopologyOrder: order, serializedPanelRecordOrder: Object.keys(envelope.snapshot.panels), measuredRightNeighbor: right ?? null }; }
function topologyNegativeEvidence(): Record<string, boolean> {
  const baseline = canonicalEnvelope() as { snapshot: { grid: { root: { type: string; data: unknown[] }; orientation: string; maximizedNode?: { location: number[] } }; panels: Record<string, unknown>; activeGroup?: string } };
  const compare = (mutate: (candidate: typeof baseline) => void) => { const candidate = structuredClone(baseline); mutate(candidate); return topologyEquals(baseline, candidate); };
  const leaves = (node: { type: string; data: unknown[] }): Array<{ type: string; data: { id: string; views: string[]; activeView?: string } }> => node.type === 'leaf' ? [node as never] : node.data.flatMap((child) => leaves(child as { type: string; data: unknown[] }));
  const reverseFirstBranch = (node: { type: string; data: unknown[] }): boolean => { if (node.type !== 'branch') return false; if (node.data.length > 1) { node.data.reverse(); return true; } return node.data.some((child) => reverseFirstBranch(child as { type: string; data: unknown[] })); };
  return {
    flattened: compare((candidate) => { candidate.snapshot.grid.root.data = leaves(candidate.snapshot.grid.root); }),
    orientationChanged: compare((candidate) => { candidate.snapshot.grid.orientation = candidate.snapshot.grid.orientation === 'HORIZONTAL' ? 'VERTICAL' : 'HORIZONTAL'; }),
    childOrderChanged: compare((candidate) => { reverseFirstBranch(candidate.snapshot.grid.root); }),
    leafChanged: compare((candidate) => { const leaf = leaves(candidate.snapshot.grid.root)[0]!; const prior = leaf.data.id; leaf.data.id = `${prior}-changed`; if (candidate.snapshot.activeGroup === prior) candidate.snapshot.activeGroup = leaf.data.id; }),
    maximizePathChanged: compare((candidate) => { const count = leaves(candidate.snapshot.grid.root).length; candidate.snapshot.grid.maximizedNode = { location: count > 1 ? [1] : [0] }; }),
  };
}
function newCoordinator(state: VoyageState) {
  const owners = new Map(Object.keys(state.panels).map((id) => [id, 'craft']));
  let committed = structuredClone(state); committedLayout = canonicalEnvelope();
  return new SurfaceOpeningCoordinator([state], {
    resolvePanel: (panel) => { const craftId = owners.get(panel.id); if (!craftId || craftId !== panel.craftId) return { reason: 'owner-mismatch' }; const resolved = resolvePanelTarget(panel.target, { craftId }, registry); return resolved.ok ? { craftId, resolved } : { reason: resolved.reason }; },
    resolveAction: (invoking, actionId) => { const key = ({ 'open-code': 'code', 'open-forms': 'forms' } as Record<string, string>)[actionId]; if (!key) return { reason: 'unknown-action' }; const resolved = resolvePanelTarget(target(key), { craftId: invoking.craftId }, registry); return resolved.ok ? { craftId: invoking.craftId, resolved, actionIdentity: `${actionId}:${invoking.craftId}` } : { reason: resolved.reason }; },
    captureValidatedLayout: canonicalEnvelope,
    applyValidatedLayout: (next) => { const baseline = new Set(runtimes.keys()); if (hasSameStructure(committed, next)) applyPresentation(next); else applyStructuralDelta(committed, next); pendingRuntimeIds = new Set([...runtimes.keys()].filter((id) => !baseline.has(id))); const envelope = canonicalEnvelope(); if (corruptNextLayout) { corruptNextLayout = false; return { ...(envelope as Record<string, unknown>), dockviewVersion: 'corrupt' }; } return envelope; },
    restoreValidatedLayout: (layout) => { restoreEnvelope(layout); disposePendingRuntimes(); },
    atomicCommit: (commit: AtomicCommit) => { if (rejectNextCommit) { rejectNextCommit = false; return false; } try { const parsed = parseDockviewEnvelope(commit.layoutSnapshot); if (!parsed.ok) throw new Error(parsed.reason); if (!topologyEquals(parsed.value, canonicalEnvelope())) throw new Error('topology-mismatch'); atomicCommits += 1; coordinatorCommands += 1; lastCommitError = ''; committed = structuredClone(commit.next); committedLayout = parsed.value; pendingRuntimeIds.clear(); for (const panel of Object.values(commit.next.panels)) owners.set(panel.id, panel.craftId); return true; } catch (error) { lastCommitError = error instanceof Error ? error.message : String(error); return false; } },
  });
}
function renderStatus() { if (!coordinator) return; const state = coordinator.state('voyage-current'); status.textContent = JSON.stringify({ revision: state.revision, history: state.history.length, cursor: state.historyCursor, activationSequence: state.activationSequence, active: api.activePanel?.id ?? null, maximized: api.activePanel?.api.isMaximized() ?? false, groups: api.groups.length, panelRecency: Object.fromEntries(Object.values(state.panels).map((panel) => [panel.id, panel.lastActivatedSequence])), canonicalHistory: state.history.every((entry) => Boolean(entry.before.layout && entry.after.layout)), topology: liveTopologyEvidence(), atomicCommits, coordinatorCommands, lastCommitError, projectionAgrees: projectionAgrees() }); document.querySelector<HTMLButtonElement>('#restore-layout')!.disabled = !state.maximizedGroupId; document.querySelector<HTMLButtonElement>('#undo-layout')!.disabled = !state.historyCursor; document.querySelector<HTMLButtonElement>('#redo-layout')!.disabled = state.historyCursor >= state.history.length; }
function initialize(width = 900) { api?.dispose(); for (const id of [...runtimes.keys()]) if (id !== 'agent') disposeRuntime(id); dockviewElement.replaceChildren(); dockviewElement.style.width = `${width}px`; atomicCommits = 0; coordinatorCommands = 0; api = createApi(); const state = baseVoyage(width); addPanel('agent', 'agent'); coordinator = newCoordinator(state); renderStatus(); }
async function open(surfaceKey: 'code' | 'forms', intent: OpenIntent) { const result = await coordinator.open({ voyageId: 'voyage-current', invokingPanelId: 'agent', actionId: `open-${surfaceKey}`, intent }); renderStatus(); return result; }
async function undo() { await coordinator.undo('voyage-current'); renderStatus(); }
async function redo() { await coordinator.redo('voyage-current'); renderStatus(); }
async function restore() { await coordinator.restore('voyage-current'); renderStatus(); }
function liveState(panelMetadata: Record<string, { sequence: number | null; surface: string }>): VoyageState { const panels: VoyageState['panels'] = {}; const groups = api.groups.map((group) => { const rect = group.element.getBoundingClientRect(); for (const item of group.panels) { const metadata = panelMetadata[item.id]!; panels[item.id] = { id: item.id, voyageId: 'voyage-current', craftId: 'craft', target: target(metadata.surface), groupId: group.id, lastActivatedSequence: metadata.sequence, runtimeId: `runtime:${item.id}` }; } return { id: group.id, panelIds: group.panels.map(({ id }) => id), activePanelId: group.activePanel!.id, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height } }; }); return { id: 'voyage-current', width: 900, revision: 0, activationSequence: 9, panels, groups, maximizedGroupId: null, history: [], historyCursor: 0 }; }
function seedSelectionScenario() { api.dispose(); dockviewElement.replaceChildren(); dockviewElement.style.width = '900px'; api = createApi(); addPanel('agent', 'agent'); addPanel('code-newer', 'code', { direction: 'below', referencePanel: 'agent' }); addPanel('code-adjacent', 'code', { direction: 'right', referencePanel: 'agent' }); const state = liveState({ agent: { sequence: 1, surface: 'agent' }, 'code-newer': { sequence: 9, surface: 'code' }, 'code-adjacent': { sequence: 2, surface: 'code' } }); coordinator = newCoordinator(state); atomicCommits = 0; coordinatorCommands = 0; renderStatus(); }

document.querySelector('#open-code-beside')!.addEventListener('click', () => void open('code', 'beside')); document.querySelector('#open-forms-beside')!.addEventListener('click', () => void open('forms', 'beside')); document.querySelector('#open-code-maximized')!.addEventListener('click', () => void open('code', 'maximized')); document.querySelector('#restore-layout')!.addEventListener('click', () => void restore()); document.querySelector('#undo-layout')!.addEventListener('click', () => void undo()); document.querySelector('#redo-layout')!.addEventListener('click', () => void redo());
document.querySelector('#scenario-adjacent')!.addEventListener('click', seedSelectionScenario);
document.querySelector('#remove-adjacency')!.addEventListener('click', () => void window.surfaceOpeningContract.removeAdjacent());
function seedTieScenario(sequence: number | null) { seedSelectionScenario(); const state = coordinator.state('voyage-current'); state.panels['code-newer']!.lastActivatedSequence = sequence; state.panels['code-adjacent']!.lastActivatedSequence = sequence; state.activationSequence = sequence ?? 1; coordinator = newCoordinator(state); renderStatus(); }
document.querySelector('#scenario-equal-ties')!.addEventListener('click', () => seedTieScenario(5));
document.querySelector('#scenario-missing-ties')!.addEventListener('click', () => seedTieScenario(null));
document.querySelector('#scenario-absent')!.addEventListener('click', () => initialize());
document.querySelector('#scenario-narrow')!.addEventListener('click', () => initialize(500));
document.querySelector('#concurrent-open')!.addEventListener('click', () => void Promise.all(Array.from({ length: 5 }, () => open('code', 'beside'))));
document.querySelector('#reject-commit')!.addEventListener('click', () => { corruptNextLayout = true; void open('code', 'beside').catch(() => { renderStatus(); }); });
document.querySelector('#evict-controller')!.addEventListener('click', () => window.surfaceOpeningContract.evictAndRestore());
document.querySelector('#persist-reload')!.addEventListener('click', () => { window.surfaceOpeningContract.persistForReload(); location.reload(); });
window.surfaceOpeningContract = { initialize, open, undo, redo, restore, rejectNext: () => { rejectNextCommit = true; }, captureAgentWindow: () => { agentWindow = runtimes.get('agent')?.element.contentWindow ?? null; }, seedSelectionScenario, removeAdjacent: async () => { const state = coordinator.state('voyage-current'); state.panels.spacer = { id: 'spacer', voyageId: state.id, craftId: 'craft', target: target('forms'), groupId: 'spacer', lastActivatedSequence: null, runtimeId: 'runtime:spacer' }; state.groups.find(({ id }) => id === state.panels.agent!.groupId)!.rect = { x: 0, y: 0, width: 200, height: 420 }; state.groups.find(({ id }) => id === state.panels['code-adjacent']!.groupId)!.rect = { x: 400, y: 0, width: 200, height: 420 }; state.groups.find(({ id }) => id === state.panels['code-newer']!.groupId)!.rect = { x: 600, y: 0, width: 300, height: 420 }; state.groups.splice(1, 0, { id: 'spacer', panelIds: ['spacer'], activePanelId: 'spacer', rect: { x: 200, y: 0, width: 200, height: 420 } }); applyProjection(state); coordinator = newCoordinator(state); await coordinator.activate(state.id, 'code-newer'); renderStatus(); }, evictAndRestore: () => { const layout = canonicalEnvelope(); api.dispose(); dockviewElement.replaceChildren(); api = createApi(); restoreEnvelope(layout); renderStatus(); }, persistForReload: () => sessionStorage.setItem(RELOAD_KEY, JSON.stringify({ state: coordinator.state('voyage-current'), layout: canonicalEnvelope() })), snapshot: () => structuredClone(api.toJSON()), topologyNegativeEvidence, observations: () => ({ ...JSON.parse(status.textContent || '{}') as Record<string, unknown>, ...liveTopologyEvidence(), atomicCommits, casWrites: atomicCommits, coordinatorCommands, lastCommitError, checkpoints: coordinator.state('voyage-current').history.length, groupPanels: api.groups.map((group) => group.panels.map(({ id }) => id)), runtimeBoots: Object.fromEntries([...runtimes].map(([id, runtime]) => [id, runtime.bootId])), runtimeActivity: Object.fromEntries(runtimeActivity), runtimeRegistrations, runtimeReleases, disposedRuntimeIds: [...disposedRuntimeIds], runtimeLayerChildren: runtimeLayer.childElementCount, agentWindowRetained: agentWindow === null || agentWindow === runtimes.get('agent')?.element.contentWindow, browserFullscreen: Boolean(document.fullscreenElement), panelRects: Object.fromEntries(api.panels.map((panel) => { const rect = panel.group.element.getBoundingClientRect(); return [panel.id, { left: rect.left, right: rect.right, width: rect.width, groupId: panel.group.id }]; })) }) };
const reload = sessionStorage.getItem(RELOAD_KEY); sessionStorage.removeItem(RELOAD_KEY); initialize(); if (reload) { const saved = JSON.parse(reload) as { state: VoyageState; layout: unknown }; restoreEnvelope(saved.layout); coordinator = newCoordinator(saved.state); renderStatus(); } status.dataset.ready = 'true';

declare global { interface Window { surfaceOpeningContract: { initialize(width?: number): void; open(surface: 'code' | 'forms', intent: OpenIntent): Promise<unknown>; undo(): Promise<void>; redo(): Promise<void>; restore(): Promise<void>; rejectNext(): void; captureAgentWindow(): void; seedSelectionScenario(): void; removeAdjacent(): Promise<void>; evictAndRestore(): void; persistForReload(): void; snapshot(): SerializedDockview; topologyNegativeEvidence(): Record<string, boolean>; observations(): Record<string, unknown> } } }
