#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const dockerEnvPath = path.join(scriptDir, '.docker.env');
const dockerEnvExamplePath = path.join(scriptDir, '.docker.env.example');
const mmctlPath = path.join(scriptDir, 'mmctl.sh');

function log(message) {
  console.log(`[mattermost-bootstrap] ${message}`);
}

function fail(message) {
  console.error(`[mattermost-bootstrap] ${message}`);
  process.exit(1);
}

function ensureDockerEnvFile() {
  if (fs.existsSync(dockerEnvPath)) {
    return;
  }

  fs.copyFileSync(dockerEnvExamplePath, dockerEnvPath);
  log(`Created ${path.basename(dockerEnvPath)} from the checked-in example`);
}

function parseEnvFile(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) {
    return env;
  }

  const content = fs.readFileSync(filePath, 'utf8');
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const equalsIndex = line.indexOf('=');
    if (equalsIndex === -1) {
      continue;
    }

    const key = line.slice(0, equalsIndex).trim();
    let value = line.slice(equalsIndex + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }

  return env;
}

function updateEnvFile(filePath, updates) {
  const existingLines = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, 'utf8').split(/\r?\n/)
    : [];
  const remaining = new Map(Object.entries(updates));
  const nextLines = existingLines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return line;
    }

    const equalsIndex = line.indexOf('=');
    if (equalsIndex === -1) {
      return line;
    }

    const key = line.slice(0, equalsIndex).trim();
    if (!remaining.has(key)) {
      return line;
    }

    const value = remaining.get(key) ?? '';
    remaining.delete(key);
    return `${key}=${value}`;
  });

  if (remaining.size > 0) {
    if (nextLines.length > 0 && nextLines[nextLines.length - 1] !== '') {
      nextLines.push('');
    }
    nextLines.push(
      '# Generated by integrations/mattermost/bootstrap-local.mjs'
    );
    for (const [key, value] of remaining) {
      nextLines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(filePath, `${nextLines.join('\n').replace(/\n+$/, '\n')}`);
}

function resolveConfig(fileEnv) {
  const read = (key, fallback = '') =>
    process.env[key] ?? fileEnv[key] ?? fallback;

  const required = (key, fallback = '') => {
    const value = read(key, fallback);
    if (!value) {
      fail(`Missing required setting: ${key}`);
    }
    return value;
  };

  const trimSlash = (value) => value.replace(/\/+$/, '');
  const slashCommandPathRaw = read(
    'MATTERMOST_BOOTSTRAP_SLASH_COMMAND_PATH',
    '/api/mattermost/slash'
  );

  return {
    baseUrl: trimSlash(read('MATTERMOST_URL', 'http://localhost:8065')),
    adminEmail: required(
      'MATTERMOST_BOOTSTRAP_ADMIN_EMAIL',
      'sysadmin@example.com'
    ),
    adminUsername: required(
      'MATTERMOST_BOOTSTRAP_ADMIN_USERNAME',
      'sysadmin'
    ),
    adminPassword: required(
      'MATTERMOST_BOOTSTRAP_ADMIN_PASSWORD',
      'Sysadmin123!'
    ),
    teamName: required('MATTERMOST_BOOTSTRAP_TEAM_NAME', 'vibe'),
    teamDisplayName: required(
      'MATTERMOST_BOOTSTRAP_TEAM_DISPLAY_NAME',
      'Vibe Kanban'
    ),
    channelName: required(
      'MATTERMOST_BOOTSTRAP_CHANNEL_NAME',
      'vibe-testing'
    ),
    channelDisplayName: required(
      'MATTERMOST_BOOTSTRAP_CHANNEL_DISPLAY_NAME',
      'Vibe Testing'
    ),
    channelPurpose: read(
      'MATTERMOST_BOOTSTRAP_CHANNEL_PURPOSE',
      'Local Vibe Kanban integration test traffic'
    ),
    botUsername: required(
      'MATTERMOST_BOOTSTRAP_BOT_USERNAME',
      'vibe-bot'
    ),
    botDisplayName: required(
      'MATTERMOST_BOOTSTRAP_BOT_DISPLAY_NAME',
      'Vibe Kanban Bot'
    ),
    botDescription: read(
      'MATTERMOST_BOOTSTRAP_BOT_DESCRIPTION',
      'Local bridge bot for the Vibe Kanban Mattermost integration'
    ),
    commandTrigger: required(
      'MATTERMOST_BOOTSTRAP_COMMAND_TRIGGER',
      'vibe'
    ),
    publicBaseUrl: trimSlash(
      read(
        'MATTERMOST_BOOTSTRAP_PUBLIC_BASE_URL',
        'http://host.docker.internal:3000'
      )
    ),
    slashCommandPath: slashCommandPathRaw.startsWith('/')
      ? slashCommandPathRaw
      : `/${slashCommandPathRaw}`,
    existingBotToken: read('MATTERMOST_BOOTSTRAP_BOT_TOKEN', ''),
    existingSlashCommandToken: read(
      'MATTERMOST_BOOTSTRAP_SLASH_COMMAND_TOKEN',
      ''
    ),
  };
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: scriptDir,
    encoding: 'utf8',
    stdio: options.stdio ?? 'pipe',
    env: {
      ...process.env,
      ...(options.env ?? {}),
    },
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    const details = `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
    const error = new Error(
      `${command} ${args.join(' ')} exited with code ${result.status}${
        details ? `\n${details}` : ''
      }`
    );
    error.stdout = result.stdout ?? '';
    error.stderr = result.stderr ?? '';
    throw error;
  }

  return result;
}

async function sleep(ms) {
  await new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function waitForMattermost(baseUrl) {
  const pingUrl = `${baseUrl}/api/v4/system/ping`;

  for (let attempt = 1; attempt <= 60; attempt += 1) {
    try {
      const response = await fetch(pingUrl);
      if (response.ok) {
        log(`Mattermost is responding on ${baseUrl}`);
        return;
      }
    } catch {
      // Keep polling until the container finishes booting.
    }

    await sleep(2000);
  }

  fail(`Timed out waiting for Mattermost at ${pingUrl}`);
}

async function apiRequest(baseUrl, pathName, options = {}) {
  const headers = {
    Accept: 'application/json',
    ...(options.body === undefined ? {} : { 'Content-Type': 'application/json' }),
    ...(options.authHeader ?? {}),
    ...(options.headers ?? {}),
  };

  const response = await fetch(`${baseUrl}/api/v4${pathName}`, {
    method: options.method ?? 'GET',
    headers,
    body: options.body === undefined ? undefined : JSON.stringify(options.body),
  });

  const text = await response.text();
  const maybeJson = text ? safeJson(text) : null;

  if (!response.ok) {
    const error = new Error(
      `HTTP ${response.status} ${options.method ?? 'GET'} ${pathName}: ${
        maybeJson?.message ?? text ?? response.statusText
      }`
    );
    error.status = response.status;
    error.body = maybeJson;
    throw error;
  }

  return {
    response,
    data: maybeJson,
  };
}

function safeJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

async function login(baseUrl, loginId, password) {
  const response = await fetch(`${baseUrl}/api/v4/users/login`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      login_id: loginId,
      password,
    }),
  });

  const text = await response.text();
  const payload = text ? safeJson(text) : null;
  if (!response.ok) {
    const error = new Error(
      `Login failed: ${payload?.message ?? text ?? response.statusText}`
    );
    error.status = response.status;
    throw error;
  }

  const token = response.headers.get('token');
  if (token) {
    return {
      authHeader: {
        Authorization: `Bearer ${token}`,
      },
    };
  }

  const setCookie = response.headers.get('set-cookie');
  if (!setCookie) {
    fail('Mattermost login succeeded but returned neither a session token nor a cookie');
  }

  return {
    authHeader: {
      Cookie: setCookie.split(';')[0],
    },
  };
}

async function ensureAdminUser(config) {
  try {
    return await login(config.baseUrl, config.adminEmail, config.adminPassword);
  } catch (error) {
    const status = error?.status;
    if (status !== 400 && status !== 401) {
      throw error;
    }
  }

  log('Creating the local Mattermost system admin via mmctl --local');
  try {
    run(mmctlPath, [
      '--local',
      'user',
      'create',
      '--email',
      config.adminEmail,
      '--username',
      config.adminUsername,
      '--password',
      config.adminPassword,
      '--system-admin',
    ]);
  } catch (error) {
    const details = `${error.stdout ?? ''}\n${error.stderr ?? ''}`;
    if (!/already exists|already in use/i.test(details)) {
      throw error;
    }
  }

  return login(config.baseUrl, config.adminEmail, config.adminPassword);
}

async function getCurrentUser(baseUrl, authHeader) {
  const result = await apiRequest(baseUrl, '/users/me', {
    authHeader,
  });
  return result.data;
}

async function findTeam(baseUrl, authHeader, teamName) {
  try {
    const result = await apiRequest(
      baseUrl,
      `/teams/name/${encodeURIComponent(teamName)}`,
      {
        authHeader,
      }
    );
    return result.data;
  } catch (error) {
    if (error.status === 404) {
      return null;
    }
    throw error;
  }
}

async function ensureTeam(baseUrl, authHeader, config) {
  const existing = await findTeam(baseUrl, authHeader, config.teamName);
  if (existing) {
    log(`Reusing team ${config.teamName}`);
    return existing;
  }

  log(`Creating team ${config.teamName}`);
  const created = await apiRequest(baseUrl, '/teams', {
    method: 'POST',
    authHeader,
    body: {
      name: config.teamName,
      display_name: config.teamDisplayName,
      type: 'O',
    },
  });
  return created.data;
}

async function findChannel(baseUrl, authHeader, teamId, channelName) {
  try {
    const result = await apiRequest(
      baseUrl,
      `/teams/${encodeURIComponent(teamId)}/channels/name/${encodeURIComponent(
        channelName
      )}`,
      {
        authHeader,
      }
    );
    return result.data;
  } catch (error) {
    if (error.status === 404) {
      return null;
    }
    throw error;
  }
}

async function ensureChannel(baseUrl, authHeader, config, teamId) {
  const existing = await findChannel(
    baseUrl,
    authHeader,
    teamId,
    config.channelName
  );
  if (existing) {
    log(`Reusing channel ${config.channelName}`);
    return existing;
  }

  log(`Creating channel ${config.channelName}`);
  const created = await apiRequest(baseUrl, '/channels', {
    method: 'POST',
    authHeader,
    body: {
      team_id: teamId,
      name: config.channelName,
      display_name: config.channelDisplayName,
      purpose: config.channelPurpose,
      type: 'O',
    },
  });
  return created.data;
}

async function listBots(baseUrl, authHeader) {
  const result = await apiRequest(baseUrl, '/bots?page=0&per_page=200', {
    authHeader,
  });
  return Array.isArray(result.data) ? result.data : [];
}

async function ensureBot(baseUrl, authHeader, config) {
  const bots = await listBots(baseUrl, authHeader);
  const existing = bots.find((bot) => bot.username === config.botUsername);
  if (existing) {
    log(`Reusing bot ${config.botUsername}`);
    return existing;
  }

  log(`Creating bot ${config.botUsername}`);
  const created = await apiRequest(baseUrl, '/bots', {
    method: 'POST',
    authHeader,
    body: {
      username: config.botUsername,
      display_name: config.botDisplayName,
      description: config.botDescription,
    },
  });
  return created.data;
}

async function ensureTeamMember(baseUrl, authHeader, teamId, userId) {
  try {
    await apiRequest(
      baseUrl,
      `/teams/${encodeURIComponent(teamId)}/members/${encodeURIComponent(userId)}`,
      {
        authHeader,
      }
    );
    return;
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }
  }

  log(`Adding user ${userId} to team ${teamId}`);
  await apiRequest(baseUrl, `/teams/${encodeURIComponent(teamId)}/members`, {
    method: 'POST',
    authHeader,
    body: {
      team_id: teamId,
      user_id: userId,
    },
  });
}

async function ensureChannelMember(baseUrl, authHeader, channelId, userId) {
  try {
    await apiRequest(
      baseUrl,
      `/channels/${encodeURIComponent(channelId)}/members/${encodeURIComponent(
        userId
      )}`,
      {
        authHeader,
      }
    );
    return;
  } catch (error) {
    if (error.status !== 404) {
      throw error;
    }
  }

  log(`Adding user ${userId} to channel ${channelId}`);
  await apiRequest(
    baseUrl,
    `/channels/${encodeURIComponent(channelId)}/members`,
    {
      method: 'POST',
      authHeader,
      body: {
        user_id: userId,
      },
    }
  );
}

async function createUserAccessToken(
  baseUrl,
  authHeader,
  userId,
  description
) {
  const created = await apiRequest(
    baseUrl,
    `/users/${encodeURIComponent(userId)}/tokens`,
    {
      method: 'POST',
      authHeader,
      body: {
        description,
      },
    }
  );
  return created.data;
}

async function listCommands(baseUrl, authHeader, teamId) {
  const result = await apiRequest(
    baseUrl,
    `/commands?team_id=${encodeURIComponent(teamId)}&custom_only=true`,
    {
      authHeader,
    }
  );
  return Array.isArray(result.data) ? result.data : [];
}

async function ensureSlashCommand(baseUrl, authHeader, config, teamId) {
  const commands = await listCommands(baseUrl, authHeader, teamId);
  const existing = commands.find(
    (command) => command.trigger === config.commandTrigger
  );
  if (existing) {
    log(`Reusing slash command /${config.commandTrigger}`);
    return existing;
  }

  const url = `${config.publicBaseUrl}${config.slashCommandPath}`;
  log(`Creating slash command /${config.commandTrigger} -> ${url}`);
  const created = await apiRequest(baseUrl, '/commands', {
    method: 'POST',
    authHeader,
    body: {
      team_id: teamId,
      method: 'P',
      trigger: config.commandTrigger,
      url,
    },
  });
  return created.data;
}

async function regenerateSlashCommandToken(
  baseUrl,
  authHeader,
  commandId
) {
  const result = await apiRequest(
    baseUrl,
    `/commands/${encodeURIComponent(commandId)}/regen_token`,
    {
      method: 'PUT',
      authHeader,
    }
  );
  return result.data?.token ?? '';
}

async function main() {
  ensureDockerEnvFile();
  const fileEnv = parseEnvFile(dockerEnvPath);
  const config = resolveConfig(fileEnv);

  log('Starting the local Mattermost docker stack');
  run('docker', ['compose', 'up', '-d'], { stdio: 'inherit' });
  await waitForMattermost(config.baseUrl);

  const session = await ensureAdminUser(config);
  const me = await getCurrentUser(config.baseUrl, session.authHeader);
  log(`Authenticated as ${me.username}`);

  const team = await ensureTeam(config.baseUrl, session.authHeader, config);
  const channel = await ensureChannel(
    config.baseUrl,
    session.authHeader,
    config,
    team.id
  );
  const bot = await ensureBot(config.baseUrl, session.authHeader, config);

  await ensureTeamMember(
    config.baseUrl,
    session.authHeader,
    team.id,
    bot.user_id
  );
  await ensureChannelMember(
    config.baseUrl,
    session.authHeader,
    channel.id,
    bot.user_id
  );

  const botToken =
    config.existingBotToken ||
    (
      await createUserAccessToken(
        config.baseUrl,
        session.authHeader,
        bot.user_id,
        `vibe-kanban-local-${new Date().toISOString()}`
      )
    ).token;

  const command = await ensureSlashCommand(
    config.baseUrl,
    session.authHeader,
    config,
    team.id
  );
  const slashCommandToken =
    config.existingSlashCommandToken ||
    (await regenerateSlashCommandToken(
      config.baseUrl,
      session.authHeader,
      command.id
    ));

  updateEnvFile(dockerEnvPath, {
    MATTERMOST_BOOTSTRAP_TEAM_ID: team.id,
    MATTERMOST_BOOTSTRAP_CHANNEL_ID: channel.id,
    MATTERMOST_BOOTSTRAP_BOT_USER_ID: bot.user_id,
    MATTERMOST_BOOTSTRAP_BOT_TOKEN: botToken,
    MATTERMOST_BOOTSTRAP_SLASH_COMMAND_ID: command.id,
    MATTERMOST_BOOTSTRAP_SLASH_COMMAND_TOKEN: slashCommandToken,
  });

  console.log('');
  log('Bootstrap complete');
  console.log(`  Mattermost URL: ${config.baseUrl}`);
  console.log(`  Team: ${config.teamName} (${team.id})`);
  console.log(`  Channel: ${config.channelName} (${channel.id})`);
  console.log(`  Bot: ${config.botUsername} (${bot.user_id})`);
  console.log(`  Slash command: /${config.commandTrigger} (${command.id})`);
  console.log(`  Slash command URL: ${config.publicBaseUrl}${config.slashCommandPath}`);
  console.log(`  Saved generated bot and slash-command tokens to ${dockerEnvPath}`);
}

main().catch((error) => {
  fail(error instanceof Error ? error.message : String(error));
});
