import { describe, expect, it } from "vitest";
import {
  createDefaultGasCityBuilderState,
  type GasCityBuilderState,
} from "./types";
import { renderGasCityGeneratedCityConfig } from "./city-config-renderer";

function builderState(
  overrides: Partial<GasCityBuilderState> = {},
): GasCityBuilderState {
  return {
    ...createDefaultGasCityBuilderState(),
    ...overrides,
  };
}

describe("renderGasCityGeneratedCityConfig", () => {
  it("renders deterministic city and rig scoped local pack imports", () => {
    const rendered = renderGasCityGeneratedCityConfig(
      builderState({
        generatedCity: {
          cityId: "default",
          cityName: "Team City",
          runtimeRoot: "/tmp/vd-gc-runtime",
          cityTomlPath: "/tmp/vd-gc-runtime/city.toml",
          lastRenderedAt: null,
        },
        localPackRefs: [
          {
            id: "disabled",
            binding: "skip_me",
            sourcePath: "/packs/skip",
            scope: "city",
            rigName: null,
            enabled: false,
            addedAt: "2026-06-11T00:00:00.000Z",
            lastValidatedAt: null,
          },
          {
            id: "rig-pack",
            binding: "review.tools",
            sourcePath: "/packs/review",
            scope: "rig",
            rigName: "frontend",
            enabled: true,
            addedAt: "2026-06-11T00:00:00.000Z",
            lastValidatedAt: null,
          },
          {
            id: "city-pack",
            binding: "gastown",
            sourcePath: "/packs/gastown",
            scope: "city",
            rigName: null,
            enabled: true,
            addedAt: "2026-06-11T00:00:00.000Z",
            lastValidatedAt: null,
          },
        ],
      }),
    );

    expect(rendered.packToml).toBe(`[pack]\nname = "Team City"\nschema = 2\n`);
    expect(rendered.cityToml).toBe(`# Generated by Vibe Dashboard Gas City Builder. Do not edit by hand.\n[workspace]\nname = "Team City"\n\n[imports.gastown]\nsource = "/packs/gastown"\n\n[[rigs]]\nname = "frontend"\n\n[rigs.imports."review.tools"]\nsource = "/packs/review"\n`);
  });

  it("rejects rig scoped imports without a rig name", () => {
    expect(() =>
      renderGasCityGeneratedCityConfig(
        builderState({
          localPackRefs: [
            {
              id: "broken",
              binding: "tools",
              sourcePath: "/packs/tools",
              scope: "rig",
              rigName: null,
              enabled: true,
              addedAt: "2026-06-11T00:00:00.000Z",
              lastValidatedAt: null,
            },
          ],
        }),
      ),
    ).toThrow(/rigName/);
  });
});
