import type { GasCityBuilderState, GasCityLocalPackRef } from "./types";

export interface GasCityGeneratedCityConfig {
  cityToml: string;
  packToml: string;
}

export function renderGasCityGeneratedCityConfig(
  state: GasCityBuilderState,
): GasCityGeneratedCityConfig {
  const cityName = state.generatedCity.cityName.trim() || "vd-generated";
  const enabledPackRefs = state.localPackRefs
    .filter((packRef) => packRef.enabled)
    .sort(comparePackRefs);
  const cityPackRefs = enabledPackRefs.filter(
    (packRef) => packRef.scope === "city",
  );
  const rigPackRefsByRig = groupRigPackRefs(enabledPackRefs);

  const cityToml: string[] = [
    "# Generated by Vibe Dashboard Gas City Builder. Do not edit by hand.",
    "[workspace]",
    `name = ${formatTomlString(cityName)}`,
  ];

  for (const packRef of cityPackRefs) {
    cityToml.push(
      "",
      `[imports.${formatTomlKeySegment(packRef.binding)}]`,
      `source = ${formatTomlString(formatSourcePath(packRef))}`,
    );
  }

  for (const [rigName, rigPackRefs] of rigPackRefsByRig) {
    cityToml.push("", "[[rigs]]", `name = ${formatTomlString(rigName)}`);
    for (const packRef of rigPackRefs) {
      cityToml.push(
        "",
        `[rigs.imports.${formatTomlKeySegment(packRef.binding)}]`,
        `source = ${formatTomlString(formatSourcePath(packRef))}`,
      );
    }
  }

  return {
    cityToml: `${cityToml.join("\n")}\n`,
    packToml: [
      "[pack]",
      `name = ${formatTomlString(cityName)}`,
      "schema = 2",
      "",
    ].join("\n"),
  };
}

function comparePackRefs(
  left: GasCityLocalPackRef,
  right: GasCityLocalPackRef,
): number {
  return (
    left.scope.localeCompare(right.scope) ||
    (left.rigName ?? "").localeCompare(right.rigName ?? "") ||
    left.binding.localeCompare(right.binding) ||
    left.sourcePath.localeCompare(right.sourcePath) ||
    left.id.localeCompare(right.id)
  );
}

function groupRigPackRefs(
  packRefs: GasCityLocalPackRef[],
): Array<[string, GasCityLocalPackRef[]]> {
  const rigPackRefsByRig = new Map<string, GasCityLocalPackRef[]>();

  for (const packRef of packRefs) {
    if (packRef.scope !== "rig") {
      continue;
    }
    const rigName = packRef.rigName?.trim();
    if (!rigName) {
      throw new Error(
        `Local pack import ${packRef.id} is rig-scoped but has no rigName.`,
      );
    }
    const existing = rigPackRefsByRig.get(rigName);
    if (existing) {
      existing.push(packRef);
    } else {
      rigPackRefsByRig.set(rigName, [packRef]);
    }
  }

  return [...rigPackRefsByRig.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
}

function formatTomlKeySegment(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    throw new Error("TOML key segment cannot be empty.");
  }
  if (/^[A-Za-z0-9_-]+$/.test(trimmed)) {
    return trimmed;
  }
  return formatTomlString(trimmed);
}

function formatSourcePath(packRef: GasCityLocalPackRef): string {
  const sourcePath = packRef.sourcePath.trim();
  if (!sourcePath) {
    throw new Error(`Local pack import ${packRef.id} has no sourcePath.`);
  }
  return sourcePath;
}

function formatTomlString(value: string): string {
  return JSON.stringify(value);
}
