import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { PackagedNativeGasCityRuntime } from './nativeGasCityRuntime';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { spawn, type ChildProcess } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:net';
import { VibeKanbanServerClient } from '../../../../server/vk-client';

const exec=promisify(execFile);
async function freePort(){return new Promise<number>((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();const port=typeof address==='object'&&address?address.port:0;server.close((error)=>error?reject(error):resolve(port));});});}
async function waitForVk(baseUrl:string){for(let attempt=0;attempt<100;attempt++){try{const response=await fetch(`${baseUrl}/health`);if(response.ok)return;}catch{}await new Promise((resolve)=>setTimeout(resolve,100));}throw new Error('VK test server did not become ready.');}

describe('packaged native Gas City runtime', () => {
  it.skipIf(process.env.VD_NATIVE_GAS_CITY_E2E !== '1')('requires exact pinned runtime and installs confirmed bytes durably', async () => {
    const base=await mkdtemp(join(tmpdir(),'vd-native-gc-'));const root=join(base,'runtime');const city=join(base,'city');await mkdir(root,{mode:0o700});await mkdir(city,{mode:0o700});
    const previous=process.env.VD_RUNTIME_ROOT;process.env.VD_RUNTIME_ROOT=base;
    try {
      const runtime=new PackagedNativeGasCityRuntime({root,city,target:'test-target',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk:{} as any,resolver:{} as any});
      await expect(runtime.health()).resolves.toEqual({ready:true});
      const bytes=new TextEncoder().encode('{"formula":{"contents":"name = \\"native-proof\\"\\n"}}\n');const digest=createHash('sha256').update(bytes).digest('hex');
      await expect(runtime.ensureBundle({operationKey:'docker-proof',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}})).resolves.toEqual({bundleRef:digest});
      expect(await readFile(join(root,'bundles',digest,'bundle.json'),'utf8')).toContain('native-proof');
      const otherBytes=new TextEncoder().encode('{"formula":{"contents":"name = \\"native-proof\\"\\ndescription = \\"different\\"\\n"}}\n');const otherDigest=createHash('sha256').update(otherBytes).digest('hex');
      const results=await Promise.allSettled([runtime.ensureBundle({operationKey:'collision-a',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}}),runtime.ensureBundle({operationKey:'collision-b',bundle:{schemaVersion:'vd.execution-bundle.v1',digest:otherDigest,bytes:otherBytes,document:{},verificationEvidence:{} as any}})]);
      expect(results.filter((entry)=>entry.status==='rejected')).toHaveLength(1);
      await rm(join(root,'bundles'),{recursive:true,force:true});await symlink('/tmp',join(root,'bundles'));
      await expect(runtime.ensureBundle({operationKey:'swap',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}})).rejects.toThrow(/server-controlled|ownership/i);
    } finally { if(previous===undefined)delete process.env.VD_RUNTIME_ROOT;else process.env.VD_RUNTIME_ROOT=previous;await rm(base,{recursive:true,force:true}); }
  });

  it.skipIf(process.env.VD_NATIVE_GAS_CITY_E2E !== '1')('runs pinned sling and authoritative Beads progression exactly once across restart',async()=>{
    const base=await mkdtemp(join(tmpdir(),'vd-native-progress-'));const home=join(base,'home'),runDir=join(base,'run'),city=join(base,'city'),rig=join(base,'rig'),runtimeRoot=join(base,'runtime');
    await Promise.all([mkdir(home,{mode:0o700}),mkdir(runDir,{mode:0o700}),mkdir(rig,{mode:0o700}),mkdir(runtimeRoot,{mode:0o700})]);const env={...process.env,HOME:home,GC_HOME:join(home,'.gc'),XDG_RUNTIME_DIR:runDir};const call=(file:string,args:string[],cwd=base)=>exec(file,args,{cwd,env,timeout:30_000,maxBuffer:2_000_000});
    const oldHome=process.env.HOME,oldRoot=process.env.VD_RUNTIME_ROOT;let vkProcess:ChildProcess|null=null,vkServerLog='';process.env.HOME=home;process.env.VD_RUNTIME_ROOT=base;
    try{
      await call('/usr/bin/git',['config','--global','user.email','native@example.test']);await call('/usr/bin/git',['config','--global','user.name','Native Test']);await call('/usr/local/bin/dolt',['config','--global','--add','user.email','native@example.test']);await call('/usr/local/bin/dolt',['config','--global','--add','user.name','Native Test']);
      await call('/usr/bin/git',['init'],rig);await call('/usr/bin/git',['config','user.email','native@example.test'],rig);await call('/usr/bin/git',['config','user.name','Native Test'],rig);await writeFile(join(rig,'README'),'native\n');await call('/usr/bin/git',['add','.'],rig);await call('/usr/bin/git',['commit','-m','init'],rig);
      await call('/usr/local/bin/gc',['init',city,'--template','empty','--no-start']);await call('/usr/local/bin/gc',['rig','add',rig,'--city',city,'--name','app','--prefix','app','--start-suspended','--json']);
      const created=JSON.parse((await call('/usr/local/bin/bd',['create','--title','Native source','--type','task','--json'],rig)).stdout);const sourceBeadId=created.id;
      const formula='formula = "native-proof"\ndescription = "Native proof"\n[requires]\nformula_compiler = ">=2.0.0"\n[catalog]\nname = "Native proof"\ndescription = "Native proof"\n[[steps]]\nid = "work"\ntitle = "Work"\ndescription = "Complete task"\n[steps.metadata]\n"gc.run_target" = "app/core.control-dispatcher"\n';
      const bytes=new TextEncoder().encode(JSON.stringify({formula:{contents:formula}}));const bundleDigest=createHash('sha256').update(bytes).digest('hex');let queueCalls=0,noteBefore=0,callbackCalls=0,callbackDelivered=false;let workspaceId='workspace-1',sessionId='session-dev';let vk:any;const binary=process.env.VD_NATIVE_GAS_CITY_VK_BINARY;
      if(binary){const port=await freePort();const assetDir=join(base,'vk-data');await mkdir(assetDir,{mode:0o700});vkProcess=spawn(binary,[],{cwd:'/workspace/vibe-kanban',env:{...env,VK_TEST_ASSET_DIR:assetDir,VK_DISABLE_EXECUTOR_PRELOAD:'1',BACKEND_PORT:String(port),PREVIEW_PROXY_PORT:String(await freePort()),HOST:'127.0.0.1',VK_QA_MODE:'1',QA_MODE:'1',VK_ALLOWED_ORIGINS:`http://127.0.0.1:${port}`,VK_QA_SCRIPTED_OUTCOME:JSON.stringify({outcome:'completed',final_message:'<decision action="done"><summary>Completed safely.</summary></decision>',delay_ms:0})},stdio:['ignore','pipe','pipe']});vkProcess.stdout?.on('data',(chunk)=>vkServerLog+=String(chunk));vkProcess.stderr?.on('data',(chunk)=>vkServerLog+=String(chunk));const apiBase=`http://127.0.0.1:${port}/api`;const client=new VibeKanbanServerClient({baseUrl:apiBase});await waitForVk(apiBase);const workspaceResponse=await fetch(`${apiBase}/workspaces`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Native proof'})});const workspaceEnvelope:any=await workspaceResponse.json();if(!workspaceResponse.ok)throw new Error(`${JSON.stringify(workspaceEnvelope)}\n${vkServerLog.slice(-4000)}`);workspaceId=workspaceEnvelope.data.id;const repo=await client.registerRepo({path:rig,display_name:'Native proof'});const branches=await client.getRepoBranches(repo.id);const branch=branches.find((candidate)=>candidate.is_current)??branches[0]!;const attach=await fetch(`${apiBase}/workspaces/${workspaceId}/repos`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repo_id:repo.id,target_branch:branch.name})});if(!attach.ok)throw new Error(`${await attach.text()}\n${vkServerLog.slice(-4000)}`);const session=await client.createSession({workspace_id:workspaceId,executor:'CODEX',name:'Dev'});sessionId=session.id;vk=client;}else{const queued=new Map<string,any>();vk={getSession:async()=>({id:sessionId,workspace_id:workspaceId}),queueFollowUp:async(currentSessionId:string,message:string,options:any)=>{const existing=queued.get(options.operationKey);if(existing)return{queued_item:existing};queueCalls++;const item={id:`queue-${queueCalls}`,session_id:currentSessionId,workspace_id:workspaceId,status:'queued',source:'workflow',priority:60,data:{message,operation_key:options.operationKey,executor_config:options.executorConfig??null,provenance:{...options.provenance,workflow_name:null,workflow_design_id:null,workflow_version:null},session_command:null}};queued.set(options.operationKey,item);return{queued_item:item};},findQueuedOperation:async(_session:string,key:string)=>queued.get(key)??null,upsertWorkflowCallback:async()=>callbackDelivered?{status:'delivered',delivered_ref:'queue-2'}:{status:'pending'},updateWorkflowCallbackStatus:async()=>{callbackCalls++;callbackDelivered=true;}};}
      const resolver:any={resolve:async()=>({ok:true,results:[{sessionId}]})};
      const runtime=new PackagedNativeGasCityRuntime({root:runtimeRoot,city,beadsDirectory:rig,target:'app/core.control-dispatcher',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk,resolver});const bundle:any={schemaVersion:'vd.execution-bundle.v1',digest:bundleDigest,bytes,document:{},verificationEvidence:{}};
      const installed=await runtime.ensureBundle({operationKey:'native-proof',bundle});const native=await runtime.ensureWorkflow({operationKey:'native-proof',bundleRef:installed.bundleRef,sourceBeadId});expect(native.status).toBe('running');expect(await runtime.checkTaskReady({workspaceId:'workspace-1',sourceBeadId})).toEqual({ready:true});
      const turnInput:any={operationKey:'native-proof',workspaceId,roleId:'dev',prompt:'Do the task.',executor:'CODEX',model:null,reasoningId:null,binding:{mode:'existing',sessionId}};const turn=await runtime.ensureRoleTurn(turnInput);try{expect(await runtime.reconcileRoleTurn(turnInput)).toEqual(turn);}catch(error:any){throw new Error(`${error.message}\n${vkServerLog.slice(-8000)}`);}if(!binary)expect(queueCalls).toBe(1);
      let typedSummary='Completed safely.';if(binary){let queued:any=null;for(let attempt=0;attempt<200;attempt++){queued=await vk.findQueuedOperation(sessionId,'native-turn:native-proof');if(queued?.status==='completed')break;if(queued?.status==='failed'||queued?.status==='cancelled')throw new Error(`VK turn ${queued.status}: ${queued.last_error??'unknown'}\n${vkServerLog.slice(-8000)}`);await new Promise((resolve)=>setTimeout(resolve,100));}expect(queued?.status).toBe('completed');expect(queued?.started_execution_process_id).toBeTruthy();const response=await vk.getExecutionProcessFinalMessage(queued.started_execution_process_id);expect(response.content).toContain('<decision action="done">');typedSummary='Completed safely.';}
      const completed=await runtime.ensureTypedResult({operationKey:'native-proof:result',...native,action:'done',summary:typedSummary});expect(completed.status).toBe('completed');const note=await runtime.ensureResultNote({operationKey:'native-proof:note',sourceBeadId,summary:typedSummary});await runtime.ensureResultNote({operationKey:'native-proof:note',sourceBeadId,summary:typedSummary});expect(note.noteRef).toMatch(/^result:/);
      const comments=JSON.parse((await call('/usr/local/bin/bd',['comments',sourceBeadId,'--json'],rig)).stdout);noteBefore=comments.length;expect(noteBefore).toBe(1);const callbackInput:any={operationKey:'native-proof:callback',request:{completionResponse:{sessionId}},run:{runId:'run',workspaceId,sourceBeadId,status:'completed',summary:'Done',url:'/run',workflowId:native.workflowId,rootBeadId:native.rootBeadId,sessionId,updatedAt:1}};await runtime.ensureTerminalCallback(callbackInput);await runtime.ensureTerminalCallback(callbackInput);if(!binary){expect(callbackCalls).toBe(1);expect(queueCalls).toBe(2);}
      const restarted=new PackagedNativeGasCityRuntime({root:runtimeRoot,city,beadsDirectory:rig,target:'app/core.control-dispatcher',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk,resolver});expect(await restarted.reconcileWorkflow({operationKey:'native-proof',bundleRef:installed.bundleRef,sourceBeadId})).not.toBe('unknown');expect(await restarted.reconcileRoleTurn(turnInput)).toEqual(turn);if(!binary)expect(queueCalls).toBe(2);vkProcess?.kill('SIGTERM');
    }finally{vkProcess?.kill('SIGKILL');await call('/usr/local/bin/bd',['dolt','stop'],rig).catch(()=>undefined);await call('/usr/local/bin/bd',['dolt','stop'],city).catch(()=>undefined);if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;if(oldRoot===undefined)delete process.env.VD_RUNTIME_ROOT;else process.env.VD_RUNTIME_ROOT=oldRoot;for(let attempt=0;attempt<5;attempt++){try{await rm(base,{recursive:true,force:true,maxRetries:3,retryDelay:100});break;}catch(error){if(attempt===4)throw error;await new Promise((resolve)=>setTimeout(resolve,200));}}}
  },120_000);
});
