import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { PackagedNativeGasCityRuntime } from './nativeGasCityRuntime';
import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { spawn, type ChildProcess } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:net';
import { VibeKanbanServerClient } from '../../../../server/vk-client';
import { NativeGasCityWorkflowProvider } from './nativeGasCityWorkflowProvider';
import { initVdDb } from '../../../../server/database';
import { Hono } from 'hono';
import { createWorkflowRegistry } from '@vibe-dashboard/workflow-core';
import { registerWorkflowRoutes } from '../../../../server/workflow-routes';
import { DbWorkflowWebhookInboxStore, signVkWebhookPayload } from '../../../../server/workflow-webhook-inbox';
import { createProductionGasCityExecutionBundleCompiler } from './gasCityExecutionBundleCompilerComposition';
import { VD_BEADS_VERSION, VD_BUNDLE_COMPILER_POLICY, VD_FORMULA_COMPILER_REQUIREMENT, VD_GAS_CITY_VERSION, VD_GC_SESSION_BRIDGE_VERSION } from './gasCityExecutionBundleCompiler';

const exec=promisify(execFile);
async function freePort(){return new Promise<number>((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();const port=typeof address==='object'&&address?address.port:0;server.close((error)=>error?reject(error):resolve(port));});});}
async function waitForVk(baseUrl:string){for(let attempt=0;attempt<100;attempt++){try{const response=await fetch(`${baseUrl}/health`);if(response.ok)return;}catch{}await new Promise((resolve)=>setTimeout(resolve,100));}throw new Error('VK test server did not become ready.');}

describe('packaged native Gas City runtime', () => {
  it.skipIf(process.env.VD_NATIVE_GAS_CITY_E2E !== '1')('requires exact pinned runtime and installs confirmed bytes durably', async () => {
    const base=await mkdtemp(join(tmpdir(),'vd-native-gc-'));const root=join(base,'runtime');const city=join(base,'city');await mkdir(root,{mode:0o700});await mkdir(city,{mode:0o700});
    const previous=process.env.VD_RUNTIME_ROOT;process.env.VD_RUNTIME_ROOT=base;
    try {
      const runtime=new PackagedNativeGasCityRuntime({root,city,target:'test-target',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk:{} as any,resolver:{} as any});
      await expect(runtime.health()).resolves.toEqual({ready:true});
      const bytes=new TextEncoder().encode('{"formula":{"contents":"name = \\"native-proof\\"\\n"}}\n');const digest=createHash('sha256').update(bytes).digest('hex');
      await expect(runtime.ensureBundle({operationKey:'docker-proof',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}})).resolves.toEqual({bundleRef:digest});
      expect(await readFile(join(root,'bundles',digest,'bundle.json'),'utf8')).toContain('native-proof');
      const otherBytes=new TextEncoder().encode('{"formula":{"contents":"name = \\"native-proof\\"\\ndescription = \\"different\\"\\n"}}\n');const otherDigest=createHash('sha256').update(otherBytes).digest('hex');
      const results=await Promise.allSettled([runtime.ensureBundle({operationKey:'collision-a',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}}),runtime.ensureBundle({operationKey:'collision-b',bundle:{schemaVersion:'vd.execution-bundle.v1',digest:otherDigest,bytes:otherBytes,document:{},verificationEvidence:{} as any}})]);
      expect(results.filter((entry)=>entry.status==='rejected')).toHaveLength(1);
      await rm(join(root,'bundles'),{recursive:true,force:true});await symlink('/tmp',join(root,'bundles'));
      await expect(runtime.ensureBundle({operationKey:'swap',bundle:{schemaVersion:'vd.execution-bundle.v1',digest,bytes,document:{},verificationEvidence:{} as any}})).rejects.toThrow(/server-controlled|ownership/i);
    } finally { if(previous===undefined)delete process.env.VD_RUNTIME_ROOT;else process.env.VD_RUNTIME_ROOT=previous;await rm(base,{recursive:true,force:true}); }
  });

  it.skipIf(process.env.VD_NATIVE_GAS_CITY_E2E !== '1')('runs pinned sling and authoritative Beads progression exactly once across restart',async()=>{
    const base=await mkdtemp(join(tmpdir(),'vd-native-progress-'));const home=join(base,'home'),runDir=join(base,'run'),city=join(base,'city'),rig=join(base,'rig'),runtimeRoot=join(base,'runtime');
    await Promise.all([mkdir(home,{mode:0o700}),mkdir(runDir,{mode:0o700}),mkdir(rig,{mode:0o700}),mkdir(runtimeRoot,{mode:0o700})]);const env={...process.env,HOME:home,GC_HOME:join(home,'.gc'),XDG_RUNTIME_DIR:runDir};const call=(file:string,args:string[],cwd=base)=>exec(file,args,{cwd,env,timeout:30_000,maxBuffer:2_000_000});
    const oldHome=process.env.HOME,oldRoot=process.env.VD_RUNTIME_ROOT;let vkProcess:ChildProcess|null=null,vkServerLog='',restartVk:(()=>Promise<ChildProcess>)|null=null;process.env.HOME=home;process.env.VD_RUNTIME_ROOT=base;
    try{
      await call('/usr/bin/git',['config','--global','user.email','native@example.test']);await call('/usr/bin/git',['config','--global','user.name','Native Test']);await call('/usr/local/bin/dolt',['config','--global','--add','user.email','native@example.test']);await call('/usr/local/bin/dolt',['config','--global','--add','user.name','Native Test']);
      await call('/usr/bin/git',['init'],rig);await call('/usr/bin/git',['config','user.email','native@example.test'],rig);await call('/usr/bin/git',['config','user.name','Native Test'],rig);await writeFile(join(rig,'README'),'native\n');await call('/usr/bin/git',['add','.'],rig);await call('/usr/bin/git',['commit','-m','init'],rig);
      await call('/usr/local/bin/gc',['init',city,'--template','empty','--no-start']);await call('/usr/local/bin/gc',['rig','add',rig,'--city',city,'--name','app','--prefix','app','--start-suspended','--json']);
      const created=JSON.parse((await call('/usr/local/bin/bd',['create','--title','Native source','--type','task','--json'],rig)).stdout);const sourceBeadId=created.id;
      let queueCalls=0,noteBefore=0,callbackCalls=0,callbackDelivered=false;let workspaceId='workspace-1',sessionId='session-dev';let vk:any;const binary=process.env.VD_NATIVE_GAS_CITY_VK_BINARY;
      if(binary){const port=await freePort();const previewPort=await freePort();const assetDir=join(base,'vk-data');await mkdir(assetDir,{mode:0o700});const apiBase=`http://127.0.0.1:${port}/api`;restartVk=async()=>{const child=spawn(binary,[],{cwd:'/workspace/vibe-kanban',env:{...env,VK_TEST_ASSET_DIR:assetDir,VK_DISABLE_EXECUTOR_PRELOAD:'1',BACKEND_PORT:String(port),PREVIEW_PROXY_PORT:String(previewPort),HOST:'127.0.0.1',VK_QA_MODE:'1',QA_MODE:'1',VK_ALLOWED_ORIGINS:`http://127.0.0.1:${port}`,VK_QA_SCRIPTED_OUTCOME:JSON.stringify({outcome:'completed',final_message:'<decision action="done"><summary>Completed safely.</summary></decision>',delay_ms:1000})},stdio:['ignore','pipe','pipe']});child.stdout?.on('data',(chunk)=>vkServerLog+=String(chunk));child.stderr?.on('data',(chunk)=>vkServerLog+=String(chunk));await waitForVk(apiBase);return child;};vkProcess=await restartVk();const client=new VibeKanbanServerClient({baseUrl:apiBase});const workspaceResponse=await fetch(`${apiBase}/workspaces`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Native proof'})});const workspaceEnvelope:any=await workspaceResponse.json();if(!workspaceResponse.ok)throw new Error(`${JSON.stringify(workspaceEnvelope)}\n${vkServerLog.slice(-4000)}`);workspaceId=workspaceEnvelope.data.id;const repo=await client.registerRepo({path:rig,display_name:'Native proof'});const branches=await client.getRepoBranches(repo.id);const branch=branches.find((candidate)=>candidate.is_current)??branches[0]!;const attach=await fetch(`${apiBase}/workspaces/${workspaceId}/repos`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repo_id:repo.id,target_branch:branch.name})});if(!attach.ok)throw new Error(`${await attach.text()}\n${vkServerLog.slice(-4000)}`);const session=await client.createSession({workspace_id:workspaceId,executor:'CODEX',name:'Dev'});sessionId=session.id;vk=client;}else{const queued=new Map<string,any>();vk={getSession:async()=>({id:sessionId,workspace_id:workspaceId}),queueFollowUp:async(currentSessionId:string,message:string,options:any)=>{const existing=queued.get(options.operationKey);if(existing)return{queued_item:existing};queueCalls++;const item={id:`queue-${queueCalls}`,session_id:currentSessionId,workspace_id:workspaceId,status:'queued',source:'workflow',priority:60,data:{message,operation_key:options.operationKey,executor_config:options.executorConfig??null,provenance:{...options.provenance,workflow_name:null,workflow_design_id:null,workflow_version:null},session_command:null}};queued.set(options.operationKey,item);return{queued_item:item};},findQueuedOperation:async(_session:string,key:string)=>queued.get(key)??null,upsertWorkflowCallback:async()=>callbackDelivered?{status:'delivered',delivered_ref:'queue-2'}:{status:'pending'},updateWorkflowCallbackStatus:async()=>{callbackCalls++;callbackDelivered=true;}};}
      const resolver:any={resolve:async()=>({ok:true,results:[{sessionId}]})};
      const runtime=new PackagedNativeGasCityRuntime({root:runtimeRoot,city,beadsDirectory:rig,target:'app/core.control-dispatcher',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk,resolver});const definition={schemaVersion:1,name:'Native proof',roles:{dev:{label:'Dev'}},initialState:'work',states:{work:{owner:'dev',steps:[{id:'decide',type:'agent_turn',turnType:'decision',prompt:{template:'Complete the selected native task and return only the decision contract.'},response:{format:'xml',schema:{format:'xsd',source:'state_actions'},invalidXmlRetry:{maxAttempts:1,prompt:'engine_default_with_validation_errors',onExhausted:'blocked'},storeRawXml:true,rawXmlMaxChars:1000,storeParsedFields:true,unknownFields:'reject_unless_allowed_by_result_contract'}}],actions:{done:{targetState:'done',result:{fields:{summary:{type:'markdown'}},required:['summary'],unknownFields:'reject'}}}},done:{terminal:true}}};const hash=(value:string)=>createHash('sha256').update(value).digest('hex');const template='Native developer template instructions.';const promptAsset='Use the confirmed workflow prompt asset.';const skillAsset='Apply the native completion skill.';const baseInstructions='Complete safely.';const bundle=await createProductionGasCityExecutionBundleCompiler().compile({schemaVersion:'vd.execution-bundle.compile-input.v1',workflow:{designId:'native-proof',version:1,definition},roles:[{roleId:'dev',template:{id:'native-developer',version:1,content:template,contentHash:hash(template)},promptAssets:[{id:'native-prompt',version:1,content:promptAsset,contentHash:hash(promptAsset)}],skillAssets:[{id:'native-skill',version:1,content:skillAsset,contentHash:hash(skillAsset)}],baseInstructions,executor:'CODEX',model:null,reasoningId:null,preferenceSources:{executor:'role_default',model:'unset',reasoningId:'unset'}}],inputs:{},taskContextPolicy:{mode:'latest_each_turn',beadIds:[sourceBeadId],include:'minimal_summary'},sessionPolicy:{mode:'run_scoped_role_sessions',incompatibleSession:'reject'},effects:{allowed:['result_note','caller_callback','notification'],closePolicy:'manual'},retry:{invalidResultAttempts:1,abruptTurnNudges:1},limits:{maxTurns:4,maxPromptChars:100000,maxResultChars:50000},compatibility:{compilerPolicy:VD_BUNDLE_COMPILER_POLICY,formulaCompiler:VD_FORMULA_COMPILER_REQUIREMENT,gasCity:VD_GAS_CITY_VERSION,beads:VD_BEADS_VERSION,bridge:VD_GC_SESSION_BRIDGE_VERSION},capabilities:['workflow.agent-turn','workflow.action-result.xml','workflow.task-context.latest','workflow.result-note','workflow.caller-callback','workflow.notification']});expect(createHash('sha256').update(bundle.bytes).digest('hex')).toBe(bundle.digest);expect(bundle.document.responseSchemas).toEqual([expect.objectContaining({stateId:'work',stepId:'decide',xsd:expect.stringContaining('<xs:schema')})]);
      const dbHandle=await initVdDb({path:join(base,'vd.sqlite')});const request:any={workspaceId,designId:'native-proof',version:1,inputs:{},roleBindings:{dev:{mode:'existing',sessionId}},beadIds:[sourceBeadId],completionResponse:{sessionId,source:'vibe-agent-cli'}};const plan:any={digest:'p'.repeat(64),workspaceId,tasks:[{id:sourceBeadId,title:'Native source'}]};
      // Exercise the real crash-before-enqueue recovery boundary. The first
      // provider persists the canonical role request and materializes GC, but
      // stops before VK is touched. A fresh provider must use those exact
      // bytes after the lease expires; it may not rebuild from the bundle.
      const crashBeforeEnqueue=new Proxy(runtime,{get(target,property,receiver){if(property==='ensureRoleTurn')return async()=>{throw new Error('simulated crash before VK enqueue');};const value=Reflect.get(target,property,receiver);return typeof value==='function'?value.bind(target):value;}}) as PackagedNativeGasCityRuntime;
      const interruptedProvider=new NativeGasCityWorkflowProvider({getDb:()=>dbHandle.db,runtime:crashBeforeEnqueue,effectLeaseMs:10,now:()=>100});expect(await interruptedProvider.checkDynamic(plan)).toEqual({ready:true});await expect(interruptedProvider.launch({request,plan,bundle,idempotencyKey:'native-proof'})).rejects.toThrow('could not be confirmed');
      const persistedBeforeEnqueue=await dbHandle.db.selectFrom('WorkflowNativeGasCityRun').selectAll().where('operationKey','=','native-proof').executeTakeFirstOrThrow();expect(persistedBeforeEnqueue.queueItemRef).toBeNull();expect(persistedBeforeEnqueue.roleTurnRequestDigest).toMatch(/^[a-f0-9]{64}$/);const canonicalRoleTurn=JSON.parse(persistedBeforeEnqueue.roleTurnRequestJson!);
      if(binary&&restartVk){await new Promise<void>((resolve)=>{vkProcess!.once('exit',()=>resolve());vkProcess!.kill('SIGTERM');});vkProcess=await restartVk();}
      const provider=new NativeGasCityWorkflowProvider({getDb:()=>dbHandle.db,runtime,effectLeaseMs:10,now:()=>1000});const recoveredBeforeEnqueue=await provider.reconcile('native-proof');expect(recoveredBeforeEnqueue).toMatchObject({outcome:'found',run:{status:'running'}});let launched=(recoveredBeforeEnqueue as any).run;expect(launched.status).toBe('running');
      const persistedAfterEnqueue=await dbHandle.db.selectFrom('WorkflowNativeGasCityRun').selectAll().where('operationKey','=','native-proof').executeTakeFirstOrThrow();expect(persistedAfterEnqueue.roleTurnRequestJson).toBe(persistedBeforeEnqueue.roleTurnRequestJson);expect(persistedAfterEnqueue.roleTurnRequestDigest).toBe(persistedBeforeEnqueue.roleTurnRequestDigest);
      // Simulate VK accepting the operation while VD loses its queue reference.
      // A second provider reconstructs from the ledger and must find the same
      // VK operation without producing another turn.
      await dbHandle.db.updateTable('WorkflowNativeGasCityRun').set({sessionId:null,queueItemRef:null,status:'ready'}).where('operationKey','=','native-proof').execute();const postEnqueueRestart=new NativeGasCityWorkflowProvider({getDb:()=>dbHandle.db,runtime,effectLeaseMs:10,now:()=>2000});const recoveredAfterEnqueue=await postEnqueueRestart.reconcile('native-proof');expect(recoveredAfterEnqueue).toMatchObject({outcome:'found',run:{status:'running'}});launched=(recoveredAfterEnqueue as any).run;expect(JSON.parse((await dbHandle.db.selectFrom('WorkflowNativeGasCityRun').select('roleTurnRequestJson').where('operationKey','=','native-proof').executeTakeFirstOrThrow()).roleTurnRequestJson!)).toEqual(canonicalRoleTurn);
      let queued:any=null;if(binary){for(let attempt=0;attempt<200;attempt++){queued=await vk.findQueuedOperation(sessionId,'native-turn:native-proof');if(queued?.status==='completed')break;if(queued?.status==='failed'||queued?.status==='cancelled')throw new Error(`VK turn ${queued.status}: ${queued.last_error??'unknown'}\n${vkServerLog.slice(-8000)}`);await new Promise((resolve)=>setTimeout(resolve,100));}expect(queued?.status).toBe('completed');expect(queued?.started_execution_process_id).toBeTruthy();expect(queued.data.message).toBe(canonicalRoleTurn.prompt);expect(queued.data.operation_key).toBe(canonicalRoleTurn.queue.operationKey);expect(queued.data.executor_config?{executor:queued.data.executor_config.executor,model_id:queued.data.executor_config.model_id??null,reasoning_id:queued.data.executor_config.reasoning_id??null}:null).toEqual(canonicalRoleTurn.executor?{executor:canonicalRoleTurn.executor,model_id:canonicalRoleTurn.model,reasoning_id:canonicalRoleTurn.reasoningId}:null);}else{queued={id:(await runtime.reconcileRoleTurn(canonicalRoleTurn) as any)?.queueItemRef,started_execution_process_id:'response-1'};}
      const app=new Hono();const secret='native-proof-secret';registerWorkflowRoutes(app,{registry:createWorkflowRegistry(),workflowHomeDb:dbHandle.db,workflowWebhookInboxStore:new DbWorkflowWebhookInboxStore({db:dbHandle.db}),vkWorkflowWebhookSecret:secret,nativeGasCityWorkflowProvider:provider,vkClient:vk,authorizeWorkflowPlan:async(_raw,authRequest)=>{if(authRequest.workspaceId!==workspaceId)throw new Error('denied');return{principalId:'native-proof',workspaceId,callerSessionId:sessionId};}});const payload={event_type:'execution.completed',delivery_id:'native-delivery-1',timestamp:new Date().toISOString(),workspace_id:workspaceId,session_id:sessionId,execution_id:queued.started_execution_process_id,queue_item_id:queued.id};const body=JSON.stringify(payload);const timestamp=Math.floor(Date.now()/1000).toString();const webhook=await app.request('/dashboard/api/workflow-webhooks/vk',{method:'POST',headers:{'content-type':'application/json','X-VK-Webhook-Timestamp':timestamp,'X-VK-Webhook-Algorithm':'hmac-sha256','X-VK-Webhook-Signature':signVkWebhookPayload(secret,timestamp,body)},body});expect(webhook.status).toBe(202);expect((await webhook.json() as any).nativeWorkflow.run.status).toBe('completed');if(binary&&restartVk){await new Promise<void>((resolve)=>{vkProcess!.once('exit',()=>resolve());vkProcess!.kill('SIGTERM');});vkProcess=await restartVk();expect((await vk.findQueuedOperation(sessionId,'native-turn:native-proof'))?.status).toBe('completed');}
      const restartedRuntime=new PackagedNativeGasCityRuntime({root:runtimeRoot,city,beadsDirectory:rig,target:'app/core.control-dispatcher',gcExecutable:'/usr/local/bin/gc',beadsExecutable:'/usr/local/bin/bd',vk,resolver});const restartedProvider=new NativeGasCityWorkflowProvider({getDb:()=>dbHandle.db,runtime:restartedRuntime});expect(await restartedProvider.reconcile('native-proof')).toMatchObject({outcome:'found'});const replay=await restartedProvider.completeRoleTurn({queueItemRef:queued.id,responseRef:queued.started_execution_process_id,finalResponseText:'<decision action="done"><summary>Completed safely.</summary></decision>'});expect(replay).toMatchObject({applied:false,run:{status:'completed'}});const status=await app.request(`/dashboard/api/workflows/native-runs/${launched.runId}?workspaceId=${workspaceId}`);expect(status.status).toBe(200);const denied=await app.request(`/dashboard/api/workflows/native-runs/${launched.runId}?workspaceId=other`);expect(denied.status).toBe(401);
      const comments=JSON.parse((await call('/usr/local/bin/bd',['comments',sourceBeadId,'--json'],rig)).stdout);noteBefore=comments.length;expect(noteBefore).toBe(1);const effects=await dbHandle.db.selectFrom('WorkflowNativeGasCityEffect').selectAll().execute();expect(effects.filter((effect)=>effect.status==='completed').map((effect)=>effect.kind).sort()).toEqual(['bundle','result_note','role_turn','terminal_callback','typed_result','workflow']);await dbHandle.db.destroy();dbHandle.sqlite.close();if(!binary){expect(callbackCalls).toBe(1);expect(queueCalls).toBe(2);}vkProcess?.kill('SIGTERM');
    }finally{vkProcess?.kill('SIGKILL');await call('/usr/local/bin/bd',['dolt','stop'],rig).catch(()=>undefined);await call('/usr/local/bin/bd',['dolt','stop'],city).catch(()=>undefined);if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;if(oldRoot===undefined)delete process.env.VD_RUNTIME_ROOT;else process.env.VD_RUNTIME_ROOT=oldRoot;for(let attempt=0;attempt<5;attempt++){try{await rm(base,{recursive:true,force:true,maxRetries:3,retryDelay:100});break;}catch(error){if(attempt===4)throw error;await new Promise((resolve)=>setTimeout(resolve,200));}}}
  },120_000);
});
