name: build_mobile

on:
  pull_request:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
          - all
          - android
          - ios
      profile:
        description: EAS build profile (preview/production)
        type: choice
        required: true
        default: preview
        options:
          - preview
          - production
      run_on_eas:
        description: Run build on EAS instead of locally in CI
        type: boolean
        default: true
      submit:
        description: Auto submit to the store? (production only)
        type: boolean
        required: false
      output_eas_build_to_logs:
        description: Output EAS build logs directly in GitHub Actions
        type: boolean
        required: false
        default: false
      site_url:
        description: Site URL used by the mobile webview bundle
        type: string
        required: true
        default: https://staging.vibekanban.app

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build mobile app with EAS
        uses: jamtools/releases/.github/actions/build_mobile_eas@dev
        with:
          local: ${{ github.event_name == 'pull_request' && 'true' || github.ref_type == 'tag' && 'false' || !inputs.run_on_eas }}
          platform: ${{ github.event_name == 'pull_request' && 'android' || github.ref_type == 'tag' && 'all' || inputs.platform }}
          profile: ${{ github.event_name == 'pull_request' && 'preview' || github.ref_type == 'tag' && 'preview' || inputs.profile }}
          submit: ${{ github.event_name == 'pull_request' && 'false' || github.ref_type == 'tag' && 'false' || inputs.submit || false }}
          output_logs: 'true' # ${{ github.event_name == 'pull_request' && 'false' || inputs.output_eas_build_to_logs || false }}
          install_command: pnpm install --frozen-lockfile
          build_command: pnpm run mobile:prepare
          mobile_directory: apps/mobile
          prebuild_command: npx expo prebuild
          site_url: ${{ github.event_name == 'pull_request' && 'https://staging.vibekanban.app' || github.ref_type == 'tag' && 'https://vibekanban.app' || inputs.site_url }}
          expo-token: ${{ secrets.EXPO_TOKEN }}
          asc_app_id: ${{ secrets.ASC_APP_ID }}
          discord_webhook_url: ${{ secrets.DISCORD_APP_BUILDS_WEBHOOK_URL }}
